### PR TITLE
tests.yaml: add KernelCI-specific tests

### PR DESCRIPTION
**Pull request by JenySadadia**
Add KernelCI tests to test catalogue as per KCIDB norms.

### CODE REVIEW

**Comment by spbnick** [comment]
This looks great, thank you, Jenny!

However, are there any better home pages for those tests, something human-oriented? Or at least could you replace the URLs pointing to the Jinja2 fiels with URLs pointing to the actual test code?

**Comment by JenySadadia** [comment]
> However, are there any better home pages for those tests, something human-oriented?

Do you mean some kind of documentation? I am sorry, we don't have it yet.

> Or at least could you replace the URLs pointing to the Jinja2 files with URLs pointing to the actual test code?

The API uses these jinja2 templates and generates test code (python scripts that we don't store) on the fly and uses them to run tests.

**Comment by spbnick** [comment]
> The API uses these jinja2 templates and generates test code (python scripts that we don't store) on the fly and uses them to run tests.

That's OK, even if complicated, but I assume the executed tests themselves have separate code, which actually tells more about what they do, and so would be more helpful for people e.g. investigating a failure, or just trying to find out about them?

**Comment by JenySadadia** [comment]
> That's OK, even if complicated, but I assume the executed tests themselves have separate code, which actually tells more about what they do, and so would be more helpful for people e.g. investigating a failure, or just trying to find out about them?

As I mentioned we don't store the test python script. Jinja2 templates are all we have atm.

> and so would be more helpful for people e.g. investigating a failure, or just trying to find out about them?

Yes, I understand. Once the documentation for tests has been added, I replace the URLs with the doc links. But currently, we don't have anything apart from these templates.

**Review by spbnick — APPROVED** [review]
Got it. Thanks, Jenny!

**Pull request merged**
