### PR TITLE
tests.yaml: add `kernelci_wifi_basic`

### PR DESCRIPTION
**Pull request by JenySadadia**
Add test to verify basic WiFi functionality on Chromebooks.

### CODE REVIEW

**Review by laura-nao — APPROVED** [review]
Looks good to me, thanks!

**Comment by spbnick** [comment]
LGTM, thanks! But the URL doesn't seem to work.

**Comment by JenySadadia** [comment]
> LGTM, thanks! But the URL doesn't seem to work.

Yes, that would work once https://github.com/kernelci/kernelci-pipeline/pull/655 is merged.
Let's wait until it gets merged.

**Comment by spbnick** [comment]
Hmmm, this URL is still giving me 404: https://github.com/kernelci/kernelci-core/blob/main/config/runtime/tests/wifi-basic.jinja2

**Comment by JenySadadia** [comment]
> Hmmm, this URL is still giving me 404: https://github.com/kernelci/kernelci-core/blob/main/config/runtime/tests/wifi-basic.jinja2

Oh, yes. The template is renamed eventually.
I need to use the new name.

**Comment by nuclearcat** [comment]
It is still in staging: https://raw.githubusercontent.com/kernelci/kernelci-core/staging.kernelci.org/config/runtime/tests/wifi-basic.jinja2

**Comment by JenySadadia** [comment]
The template has been merged now.

**Pull request merged**
