### PR TITLE
postgresql: Fix errors in docs

### PR DESCRIPTION
**Pull request by mrbazzan**
Concerns #305

### CODE REVIEW

**Comment by mrbazzan** [comment]
CC: @spbnick 
Some trivial things I also noticed:
1) These [lines](https://github.com/kernelci/kcidb/blob/a6fdb0b47138fdaed0b6847c06fb149199c1966e/kcidb/db/postgresql/schema.py#L239-L241) seem incoherent. It should be simplified.

2) Why did you use this [format ](https://github.com/kernelci/kcidb/blob/a6fdb0b47138fdaed0b6847c06fb149199c1966e/kcidb/db/postgresql/__init__.py#L83-L90) and not something like the one below?
```python
        with self.conn, self.conn.cursor() as cursor:
             try:
                cursor.execute("SELECT get_version()")
                version = cursor.fetchone()[0]
                return int(version / 1000), int(version % 1000)
             # It's auto-generated, pylint: disable=no-member
             except psycopg2.errors.UndefinedFunction:
                return 0, 0
```

**Comment by spbnick** [comment]
Thanks a lot for the fixes, @mrbazzan! Merging :relaxed:

**Review by spbnick — APPROVED** [review]

**Comment by spbnick** [comment]
> CC: @spbnick Some trivial things I also noticed:
> 
>     1. These [lines](https://github.com/kernelci/kcidb/blob/a6fdb0b47138fdaed0b6847c06fb149199c1966e/kcidb/db/postgresql/schema.py#L239-L241) seem incoherent. It should be simplified.

Do you mean it's hard to understand? If yes, then how about this:

```python
        """
        Format the "INSERT/UPDATE" command template for loading a row into a
        database, observing deduplication logic.

        Args:
            name:       The name of the target table of the command.
            prio_db:    If true, format the UPDATE part of the command so that
                        the values already in the database take priority over
                        the loaded ones, and vice versa otherwise.
        Returns:
            The formatted "INSERT/UPDATE" command template, expecting
            parameters packed by the pack() method.
        """
```

>     2. Why did you use this [format ](https://github.com/kernelci/kcidb/blob/a6fdb0b47138fdaed0b6847c06fb149199c1966e/kcidb/db/postgresql/__init__.py#L83-L90) and not something like the one below?
> 
> 
> ```python
>         with self.conn, self.conn.cursor() as cursor:
>              try:
>                 cursor.execute("SELECT get_version()")
>                 version = cursor.fetchone()[0]
>                 return int(version / 1000), int(version % 1000)
>              # It's auto-generated, pylint: disable=no-member
>              except psycopg2.errors.UndefinedFunction:
>                 return 0, 0
> ```

Hmm, no reason in particular. I would say they do mostly the same thing.
Do you think one is better than the other?

**Comment by mrbazzan** [comment]
> > CC: @spbnick Some trivial things I also noticed:
> > ```
> > 1. These [lines](https://github.com/kernelci/kcidb/blob/a6fdb0b47138fdaed0b6847c06fb149199c1966e/kcidb/db/postgresql/schema.py#L239-L241) seem incoherent. It should be simplified.
> > ```
> 
> Do you mean it's hard to understand? If yes, then how about this:
> 
> ```python
>         """
>         Format the "INSERT/UPDATE" command template for loading a row into a
>         database, observing deduplication logic.
> 
>         Args:
>             name:       The name of the target table of the command.
>             prio_db:    If true, format the UPDATE part of the command so that
>                         the values already in the database take priority over
>                         the loaded ones, and vice versa otherwise.
>         Returns:
>             The formatted "INSERT/UPDATE" command template, expecting
>             parameters packed by the pack() method.
>         """
> ```
> 

Perfect! I'll create a PR to that effect.

> > ```
> > 2. Why did you use this [format ](https://github.com/kernelci/kcidb/blob/a6fdb0b47138fdaed0b6847c06fb149199c1966e/kcidb/db/postgresql/__init__.py#L83-L90) and not something like the one below?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> >         with self.conn, self.conn.cursor() as cursor:
> >              try:
> >                 cursor.execute("SELECT get_version()")
> >                 version = cursor.fetchone()[0]
> >                 return int(version / 1000), int(version % 1000)
> >              # It's auto-generated, pylint: disable=no-member
> >              except psycopg2.errors.UndefinedFunction:
> >                 return 0, 0
> > ```
> 
> Hmm, no reason in particular. I would say they do mostly the same thing. Do you think one is better than the other?

No, all the other instance of doing something like this in `postgresql` db used something like the format I specified. So, I just wanted to know if there was a reason for changing it.

**Comment by spbnick** [comment]
> No, all the other instance of doing something like this in postgresql db used something like the format I specified. So, I just wanted to know if there was a reason for changing it.

Ah, I see. Yeah makes sense to have the same approach everywhere. Perhaps on the next refactoring we'll clean that up. Meanwhile it should be good enough. Thanks!

**Pull request merged**
