### PR TITLE
Update submitter guide to use v4.1 schema

### PR DESCRIPTION
**Pull request by NikkyXO**
Added sections to v4.1 schema in submitter_guide.md

### CODE REVIEW

**Comment by NikkyXO** [comment]
@spbnick  i added the section part

**Comment by spbnick** [comment]
Thank you, @NikkyXO.

I see you've added descriptions of the objects pulled from the schema. While this is a good start, this guide needs a little more understanding and insight into the purpose and function of those objects and properties. The submitters can go into the schema themselves and see those descriptions. The guide needs to give something more than that: it needs to ease them into it. Give a basic and approachable explanation of the essentials and withhold unnecessary details.

However, that's perhaps too much to expect from a newcomer both to the project, and to the kernel development and to CI workflow in general. Let's put this aside for now, we don't have much of the contribution period left. Please pick another issue, working more on the code, something you would be comfortable with. Tell me, if you can't find anything suitable, and I can perhaps add some more issues.

P.S. We already have sections for checkouts, builds, and issues in the document, if you scroll below your addition. We needed to add the two new sections after those.
P.P.S. Your new changes seem to be based on the state of the repository before your previous change we already merged. You needed to update your repo (e.g. with `git pull --rebase`) before posting this. Just something to watch out for later.

**Comment by NikkyXO** [comment]
> Thank you, @NikkyXO.
> 
> I see you've added descriptions of the objects pulled from the schema. While this is a good start, this guide needs a little more understanding and insight into the purpose and function of those objects and properties. The submitters can go into the schema themselves and see those descriptions. The guide needs to give something more than that: it needs to ease them into it. Give a basic and approachable explanation of the essentials and withhold unnecessary details.
> 
> However, that's perhaps too much to expect from a newcomer both to the project, and to the kernel development and to CI workflow in general. Let's put this aside for now, we don't have much of the contribution period left. Please pick another issue, working more on the code, something you would be comfortable with. Tell me, if you can't find anything suitable, and I can perhaps add some more issues.
> 
> P.S. We already have sections for checkouts, builds, and issues in the document, if you scroll below your addition. We needed to add the two new sections after those. P.P.S. Your new changes seem to be based on the state of the repository before your previous change we already merged. You needed to update your repo (e.g. with `git pull --rebase`) before posting this. Just something to watch out for later.

Thanks @spbnick  I will update my repo to get the recent changes. i just checked through the issues  but i'm having problems picking one to work on because a lot of them seems to have a person assigned already.  Please guide me to available issues that has more on the code part.

**Comment by spbnick** [comment]
We have a few "[good second issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+no%3Aassignee+repo%3Akernelci%2Fkcidb-io+repo%3Akernelci%2Fkcidb+label%3A%22good+second+issue%22)" remaining, but try taking a look at #377, and see if you can figure out and convert one test of your choosing for the start.

**Comment by spbnick** [comment]
Closing this for now to keep the list of PRs cleaner.

**Pull request closed without merging**
