### PR TITLE
io.schema: Prohibit directories in resource names

### PR DESCRIPTION
**Pull request by spbnick**

### CODE REVIEW

**Comment by khilman** [comment]
I don't have a strong opinion on this, but it seems a bit restrictive to me at this stage.  Why refuse directories?

If this is just going to be used for arbitrary resrouces (e.g. input/output files) it seems a bit premature to prohibit completely.

**Comment by spbnick** [comment]
@khilman, if we want to let people download individual files from our eventual result file server, then we won't be able to preserve the directory names from the "name" in the download response headers (`Content-Disposition: filename=<NAME>`), it will be lost.

**Comment by spbnick** [comment]
I just saw our database pushing names with directories, submitted an issue internally, and would like to prevent that from happening again.

**Comment by khilman** [comment]
OK, makes sense, thanks for explanation.  I don't think staging.kernelci.org is currently pushing any directories currently.  If so, we'll have to fixup.

**Comment by spbnick** [comment]
@khilman, I didn't see that from kernelci, just CKI test output files.

**Pull request merged**
