### PR TITLE
Add check for bucket existence before creation

### PR DESCRIPTION
**Pull request by octonawish-akcodes**
Added a check for bucket before creation.

Need reviews @spbnick

### CODE REVIEW

**Comment by spbnick** [comment]
We don't need to do this in the Python client, but when deploying the bucket in the `cloud` script, instead.

**Review by spbnick — CHANGES_REQUESTED** [review]
LGTM, except please add `TMPDIR="$TMPDIR_ORIG" ` to both of the commands you added, as I've requested on our call today. Otherwise they can produce the error we saw before. Thank you!

**Comment by octonawish-akcodes** [comment]
Done!

**Comment by spbnick** [comment]
LGTM, but please fix the commit subject. We're checking for "bucket" existence, not storage. And we don't do that in the cache client.

**Comment by octonawish-akcodes** [comment]
> LGTM, but please fix the commit subject. We're checking for "bucket" existence, not storage. And we don't do that in the cache client.

Looks good now?

**Review by spbnick — APPROVED** [review]

**Pull request merged**
