### PR TITLE
Add dummy issue editor service and package

### PR DESCRIPTION
**Pull request by spbnick**
Heads-up @helen-fornazier. This is WIP ATM.

### CODE REVIEW

**Comment by spbnick** [comment]
OK, my manual partial deployment to staging (with namespace `iss-ed-test2`)  worked, and I was able to connect to the server on http://localhost:8080 after starting the proxy like this:

```bash
gcloud beta run services proxy --project kernelci-staging iss-ed-test2-kcidb-iss-ed --region=us-central1
```

For reference the partial deployment was done with this command:
```bash
./cloud deploy 'kernelci-staging' 'iss_ed_test2' --smtp-mocked -v --test -s '@(iam|artifacts|pubsub|secrets|run)'
```

@helen-fornazier, please feel free to try it out. You'll need to figure out how to do a deployment. You can take a look at the GitHub actions for reference, and I can answer your questions later today.

To redeploy after updates to the code you'll need to deploy `artifacts` and `run` "sections". This will rebuild and redeploy all containers. We can work on making it more granular later, so it's faster.

Please review and give me questions :grin:

**Comment by spbnick** [comment]
Once we get it working, we can enable user access to the issue editor by giving them permissions to connect to and trigger this service.

**Comment by spbnick** [comment]
And yes, we can merge this dummy, once we check everything is to our satisfaction, and you can work on the implementation in successive PRs.

**Comment by helen-fornazier** [comment]
> OK, my manual partial deployment to staging (with namespace `iss-ed-test2`) worked, and I was able to connect to the server on http://localhost:8080 after starting the proxy like this:
> 
> ```shell
> gcloud beta run services proxy --project kernelci-staging iss-ed-test2-kcidb-iss-ed --region=us-central1
> ```
> 
> (you could try the above as well).

This works for me (sorry my delay, I had to fix a few things in my gcloud installation). But it didn't ask for any authentication.

> 
> For reference the partial deployment was done with this command:
> 
> ```shell
> ./cloud deploy 'kernelci-staging' 'iss_ed_test2' --smtp-mocked -v --test -s '@(iam|artifacts|pubsub|secrets|run|psql)'
> ```
> 

I get this error /home/ccu/ccu/kcidb/kcidb/kcidb/cloud/misc.sh: line 130: kcidb-db-init: command not found

Could you point me how to install it? I couldn't find in the docs.

> @helen-fornazier, please feel free to try it out. You'll need to figure out how to do a deployment. You can take a look at the GitHub actions for reference, and I can answer your questions later today.

Sure, we can use it to do the deploy when updating the repo.

> 
> To redeploy after updates to the code you'll need to deploy `artifacts` and `run` "sections". This will rebuild and redeploy all containers. We can work on making it more granular later, so it's faster.

ok

> 
> Please review and give me questions 😁

**Comment by spbnick** [comment]
I generally install KCIDB with `pip3 install --break-system-packages --user -e .` for development. But a venv should work as well. After you install it (and provided you have the binary path in your `PATH`, so your shell could find the tools like `kcidb-db-init`), you should be able to execute the `cloud` script no problem.

I deleted that manual deployment, so staging is not so crowded, and because you were occupied with other things. You can try to make your own deployment there.

The proxy uses the credentials you supplied when using `gcloud auth login` or some such.

Also, if you feel anything is missing from the docs, now would be a great time to add it :grin:!

**Comment by helen-fornazier** [comment]
@spbnick I managed to deploy it, and to access it I need to execute:

```
curl -H "Authorization: Bearer $(gcloud auth print-identity-token)" https://iss-ed-test2-kcidb-iss-ed-z47nqds5jq-uc.a.run.app
```

I guess we need to setup Cloud Identity-Aware Proxy (IAP) to make it easier to access ?

**Comment by spbnick** [comment]
@helen-fornazier, this is how to make an authenticated request to it, which doesn't really work in a browser directly. You need to run the proxy, as I described above, to be able to use the web browser.

**Comment by helen-fornazier** [comment]
> @helen-fornazier, yes, this is how to make an authenticated request to it, which doesn't really work in a browser directly. You need to run the proxy, as I described above, to be able to use the web browser.

ah, I see, I thought that was deploying locally or something, but it actually enables a proxy to access the page on localhost, ok, got it now. Cool! I guess we can work like that.

lgtm, I guess we can merge it and I'll send PRs updating kcidb/cloud/iss-ed then.

I quickly took a look at the commits, looks fine, but I don't have much familiarity to check if everything is correct.

In any case: Acked-by: Helen Koike <helen.koike@collabora.com

**Comment by spbnick** [comment]
Give me your review, then :grin:

**Comment by helen-fornazier** [comment]
> Give me your review, then 😁

Reviewed-by: Helen Koike <helen.koike@collabora.com>

:)

**Review by helen-fornazier — APPROVED** [review]

**Comment by helen-fornazier** [comment]
> Give me your review, then 😁

I did, but I guess I need write access from this message:

"At least 1 approving review is required by reviewers with write access. "

**Comment by spbnick** [comment]
> I did, but I guess I need write access from this message:

You will, once you confirm the invitation I sent you yesterday :grin:

**Comment by spbnick** [comment]
Anyway, merging! Thanks for the review :relaxed:

**Pull request merged**
