### PR TITLE
Add PostgreSQL driver

### PR DESCRIPTION
**Pull request by spbnick**

### CODE REVIEW

**Comment by spbnick** [comment]
@mrbazzan, do you think you could take a look at this one as well?

**Comment by mrbazzan** [comment]
> @mrbazzan, do you think you could take a look at this one as well?

Sure!

**Comment by spbnick** [comment]
@mrbazzan, I'll have to merge this as is for now, but I would be glad to fix any issues you find afterwards.

**Comment by mrbazzan** [comment]
> @mrbazzan, I'll have to merge this as is for now, but I would be glad to fix any issues you find afterwards.

Okay.

**Pull request merged**
