### PR TITLE
Add storage block fs fio and queue scheduler tests to kcidb catalog

### PR DESCRIPTION
**Pull request by juanje**
RH recently onboarded two storage block tests, one for filesystem fio and other for queue scheduler, please add this test descriptons to the KCIDB catalog.

### CODE REVIEW

**Comment by spbnick** [comment]
Thank you, @juanje! This looks good to me, but please fix the ordering issue the CI has spotted.

**Comment by juanje** [comment]
Oh, I thought about the title and I forgot that the code didn't have the `storage`part. I'll fix it right away.
Thanks!

**Comment by juanje** [comment]
Sorry, apparently I don't know how to sort... :disappointed: 
I'll try again.

**Comment by spbnick** [comment]
Thank you, @juanje :smiley:!

**Pull request merged**
