### PR TITLE
[Close #110] Upgrade google-cloud pubsub dependency

### LINKED ISSUE #110: Upgrade google-cloud-pubsub dependency
The latest release of the `google-cloud-pubsub` package breaks the existing KCIDB code, and was pinned to versions <2.0.0dev.

Fix the incompatibilities and unpin the package. Or perhaps re-pin to <3.0.0dev.

### PR DESCRIPTION
**Pull request by mharyam**
Fix #110 

1) Upgrade API completely

### CODE REVIEW

**Review by spbnick — CHANGES_REQUESTED** [review]
This looks pretty good so far, but before I test it, could you please squash the two commits into one (as they don't make sense and won't work without each other), and rebase on top of the latest main?

Thank you!

**Comment by spbnick** [comment]
Oh, and also, please address the issues CI found. Thanks!

**Comment by mharyam** [comment]
> Oh, and also, please address the issues CI found. Thanks!

I have squashed it and fixed the issue with CI

**Comment by spbnick** [comment]
Thank you, Maryam! Could you also rebase your commit on top of the latest `main` branch? It's a bit behind on what's been going on.

**Comment by spbnick** [comment]
Nevermind, I just tested the change locally, and it seems to work, so we'd better go ahead and finish it quickly. I rebased it for you. Let's see what CI says. And then I'll merge and try to deploy it, and we'll see :smiley:

**Comment by spbnick** [comment]
CI is happy so far, let's see how the deployment goes. Thanks a lot for seeing this through, Maryam!

**Pull request merged**
